name: Setup PXE Host

on:
  workflow_dispatch:

jobs:
  setup-pxe-host:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and config dependencies
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y httpd"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y tftp-server"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y syslinux-tftpboot"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --permanent --add-service=http"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --permanent --add-service=tftp"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --reload"

      - name: Deploy PXE config and Kickstart to PXE Host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo mkdir -p /var/lib/tftpboot/pxelinux"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo cp /tftpboot/* /var/lib/tftpboot/pxelinux"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo mkdir -p /var/lib/tftpboot/pxelinux/pxelinux.cfg"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "scp -r pxe/pxelinux.cfg ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:/var/lib/tftpboot/pxelinux/pxelinux.cfg"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo curl -o /var/lib/tftpboot/vmlinuz http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/images/pxeboot/vmlinuz"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo curl -o /var/lib/tftpboot/initrd.img http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/images/pxeboot/initrd.img"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "scp kickstart/anaconda-ks.cfg ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:/var/www/html/
            
    #   - name: Enable and start services
    #     run: |
    #       ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo systemctl enable --now httpd"
    #       ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo systemctl enable --now tftp.socket"