name: Setup PXE Host

on:
  workflow_dispatch:

jobs:
  setup-pxe-host:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install HTTP Server on PXE host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y httpd"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo systemctl enable --now httpd"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --permanent --add-service=http"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --reload"

      - name: Install TFTP Server on PXE host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y tftp-server"
          # Enable and start tftp service (name differs by distro)
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo systemctl enable --now tftp.socket"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --permanent --add-service=tftp"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo firewall-cmd --reload"

      - name: Install PXE bootloader files on PXE host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "sudo dnf install -y syslinux-tftpboot"
          # Enable and start services
          sudo systemctl enable --now tftp.socket

      - name: Prepare minimal PXE files
        run: |
          mkdir -p output/pxelinux.cfg
          cp pxe/pxelinux.cfg/default output/pxelinux.cfg/default
          cp kickstart/anaconda-ks.cfg output/ks.cfg

      - name: Deploy PXE config and Kickstart to PXE Host
        run: |
          scp -r output/* $PXE_USER@$PXE_HOST:/tmp/pxe/
          ssh $PXE_USER@$PXE_HOST <<'EOF'
            sudo mkdir -p /var/lib/tftpboot/pxelinux.cfg

            # Use syslinux files already provided by syslinux-tftpboot
            sudo cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/
            sudo cp /usr/share/syslinux/ldlinux.c32 /var/lib/tftpboot/

            # Download CentOS 9 PXE boot kernel/initrd directly on PXE host
            sudo curl -o /var/lib/tftpboot/vmlinuz http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/images/pxeboot/vmlinuz
            sudo curl -o /var/lib/tftpboot/initrd.img http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/images/pxeboot/initrd.img

            # Move PXE config and ks.cfg
            sudo mv /tmp/pxe/pxelinux.cfg/default /var/lib/tftpboot/pxelinux.cfg/
            sudo mv /tmp/pxe/ks.cfg /var/www/html/
          EOF